### PR TITLE
Add positional argument specifiers for format

### PR DESCRIPTION
**Pull request by shurl**
Allows compatibility with Python 2.6

### CODE REVIEW

**Comment by tamentis** [comment]
Thanks!

**Comment by tamentis** [comment]
Is that only thing stopping it from running on Python 2.6?

**Comment by shurl** [comment]
As far as I could tell from my testing, yes. I'm happy to create further PR's if I find any other issues and am able to fix.

**Comment by tamentis** [comment]
Alright, I lowered the requirements to Python 2.6.

**Comment by harryperks** [comment]
Hi @tamentis are you able to release this new package on pypi please? We have a few customers waiting on this so it'd be great to see this published soon!

**Comment by tamentis** [comment]
Of course, I'll do that today.

**Comment by tamentis** [comment]
There you go: https://pypi.python.org/pypi/mdstat/1.0.4

**Comment by harryperks** [comment]
Thanks!

**Pull request merged**
